### ISSUE TITLE
unexpected token '.'for index.css

### ISSUE THREAD

**Issue by jerome-diver** [JakeHartnell/react-images-upload#240]
Babel is not happy the way you import index.css in my application.
It does works one time, but no more now... i have no clue why, but i think it is in relation with the fact i use a SSR web site code, and the way you are including .css file should be unaccepted in client side.
Do you have an idea how to fix this ?

**Comment by PaulAtkins88** [comment]
Same here breaks on .fileUploader
`node_modules\react-images-upload\index.css:1
.fileUploader {
^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:984:16)
    at Module._compile (internal/modules/cjs/loader.js:1032:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)`

**Comment by haroonali72** [comment]
Facing the same issue. Any fix ?
