### ISSUE TITLE
"SyntaxError: Unexpected token ." while importing css file

### ISSUE THREAD

**Issue by msuvojit** [JakeHartnell/react-images-upload#98]
I am getting following error while using the library

/home/suvo/projects/startup/selsy-dashboard/node_modules/react-images-upload/index.css:1
 (function (exports, require, module, __filename, __dirname) { .fileUploader {
                                                               ^
  SyntaxError: Unexpected token .
     at createScript (vm.js:80:10)
     at Object.runInThisContext (vm.js:139:10)
     at Module._compile (module.js:616:28)
     at Object.Module._extensions..js (module.js:663:10)
     at Module.load (module.js:565:32)
     at tryModuleLoad (module.js:505:12)
     at Function.Module._load (module.js:497:3)
     at Module.require (module.js:596:17)
     at require (internal/module.js:11:18)
     at Object.<anonymous> (/home/suvo/projects/startup/selsy-dashboard/node_modules/react-images-upload/compiled.js:17:1)
     at Module._compile (module.js:652:30)
     at Object.Module._extensions..js (module.js:663:10)
     at Module.load (module.js:565:32)
     at tryModuleLoad (module.js:505:12)
     at Function.Module._load (module.js:497:3)
     at Module.require (module.js:596:17)
     at require (internal/module.js:11:18)
     at npmRequire (/home/suvo/projects/startup/selsy-dashboard/.meteor/local/build/programs/server/npm-require.js:133:10)
     at Module.useNode (packages/modules-runtime.js:664:18)
     at compiled.js (packages/modules.js:1239:8)
     at fileEvaluate (packages/modules-runtime.js:336:7)
     at Module.require (packages/modules-runtime.js:238:14)

**Comment by theallseingeye** [comment]
@msuvojit how did you fix this? I'm hitting this

**Comment by msuvojit** [comment]
I was using this library with Meteor.js and react with server-side rendering. So while the CSS import code was running on the server side then it was throwing an error. So I add a condition to check if the code was running on the client side then only the CSS import would happen. 
Can you please explain your problem?

**Comment by Aid19801** [comment]
I have a similar issue. Server Side Rendering hates the CSS file. No idea why. there's other css files in various node mods. just seems to hate this one 😂

**Comment by khoirulhasin** [comment]
use dynamic to import

```
const ImageUploader = dynamic(
	() => import('react-images-upload').then(mod => mod.ImageUploader),
	{ ssr: false }
)

```

**Comment by meetsmarttechnica** [comment]
i really need help
